version: '3'
services:
  server:
    build: ./server
    ports:
      - "3001:3001"
    depends_on:
      - mongo
    env_file:
      - ./server/.env.docker
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_db:/data/db
    environment:
      - MONGO_INITDB_DATABASE=mydatabase
  client:
    build: ./client
    ports:
      - "3000:3000"

volumes:
  mongo_db:
