version: '3'
services:
  server:
    build: ./server
    image: muhammadhur/test-khabib-server:latest
    ports:
      - "3001:3001"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/mydatabase
      - SECRET=secret123
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_db:/data/db
    environment:
      - MONGO_INITDB_DATABASE=mydatabase
  client:
    build: ./client
    image: muhammadhur/test-khabib-client:latest
    ports:
      - "3000:3000"

volumes:
  mongo_db:
