version: '3'
services:
  app:
    build: ./server
    ports:
      - "3001:3001"
    depends_on:
      - mongo
    env_file:
      - ./server/.env
  mongo:
    image: mongo:latest
    ports:
      - "27018:27018"
    volumes:
      - mongo_db:/data/db
    environment:
      - MONGO_INITDB_DATABASE=mydatabase
volumes:
  mongo_db:
